
CREATE MATERIALIZED VIEW cvr.cvr_jur_adresser AS
SELECT
  stam.modifikationsstatus,
  stam.cvrnr,
  stam.livsforloeb_startdato,
  stam.livsforloeb_ophoersdato,
  stam.ajourfoeringsdato,
  stam.reklamebeskyttelse,
  stam.navn_gyldigfra,
  stam.navn_tekst,

  hist.beliggenhedsadresse_gyldigfra,
  hist.beliggenhedsadresse_vejnavn,
  hist.beliggenhedsadresse_vejkode,
  hist.belig_adresse_husnummerfra,
  hist.belig_adresse_husnummertil,
  hist.beliggenhedsadresse_bogstavfra,
  hist.beliggenhedsadresse_bogstavtil,
  hist.beliggenhedsadresse_etage,
  hist.beliggenhedsadresse_sidedoer,
  hist.beliggenhedsadresse_postnr,
  hist.belig_adresse_postdistrikt,
  hist.beliggenhedsadresse_bynavn,
  hist.kommune_kode,
  hist.kommune_tekst,
  hist.beliggenhedsadresse_postboks,
  hist.beliggenhedsadresse_conavn,
  hist.belig_adresse_adr_fritekst,

  stam.postadresse_gyldigfra,
  stam.postadresse_vejnavn,
  stam.postadresse_vejkode,
  stam.postadresse_husnummerfra,
  stam.postadresse_husnummertil,
  stam.postadresse_bogstavfra,
  stam.postadresse_bogstavtil,
  stam.postadresse_etage,
  stam.postadresse_sidedoer,
  stam.postadresse_postnr,
  stam.postadresse_postdistrikt,
  stam.postadresse_bynavn,
  stam.postadresse_kommune_kode,
  stam.postadresse_kommune_tekst,
  stam.postadresse_postboks,
  stam.postadresse_conavn,
  stam.postadresse_adressefritekst,
  stam.virksomhedsform_gyldigfra,
  stam.virksomhedsform_kode,
  stam.virksomhedsform_tekst,
  stam.virk_form_ans_datalev,
  stam.hovedbranche_gyldigfra,
  stam.hovedbranche_kode,
  stam.hovedbranche_tekst,
  stam.bibranche1_gyldigfra,
  stam.bibranche1_kode,
  stam.bibranche1_tekst,
  stam.bibranche2_gyldigfra,
  stam.bibranche2_kode,
  stam.bibranche2_tekst,
  stam.bibranche3_gyldigfra,
  stam.bibranche3_kode,
  stam.bibranche3_tekst,
  stam.telefonnummer_gyldigfra,
  stam.telefonnummer_kontaktoplysning,
  stam.telefax_gyldigfra,
  stam.telefax_kontaktoplysning,
  stam.email_gyldigfra,
  stam.email_kontaktoplysning,
  stam.kreditoplysning_gyldigfra,
  stam.kreditoplysning_tekst,
  stam.aarsbeskaeftigelse_aar,
  stam.aarsbes_antalansatte,
  stam.aarsbes_antansatteinterval,
  stam.aarsbes_antalaarsvaerk,
  stam.aarsbes_antaarsvaerkinterval,
  stam.aarsbes_antalinclejere,
  stam.aarsbes_antinclejereinterval,
  stam.kvartalsbeskaeftigelse_aar,
  stam.kvartalsbeskaeftigelse_kvartal,
  stam.kvartalsbes_antansatte,
  stam.kvartalsbes_antansatteinterval,
  stam.kvartalsbes_antalaarsvaerk,
  stam.kvartalsbes_antaarsvaerkinterval,
  stam.maanedsbeskaeftigelse_aar,
  stam.maanedsbeskaeftigelse_maaned,
  stam.maanedsbeskaeftigelse_antalansatte,
  stam.maanedsbeskaeftigelse_antalansatteinterval,
  stam.maanedsbeskaeftigelse_antalaarsvaerk,
  stam.maanedsbeskaeftigelse_antalaarsvaerkinterval,
  stam.produktionsenheder,
  stam.deltagere,
  stam.produktionsenheder_gyldigfra,

  hist.tilnaermethusnr,
  hist.geokodningskvalitet,
  hist.koornord,
  hist.kooroest,
  hist.lat,
  hist.long,
  hist.vejkode,
  hist.hus_nr,
  hist.husnr,
  hist.adr2,
  hist.lifasystemid,
  hist.indlaest_dato,
  hist.geom,
  hist.gid,
  hist.kilde
  FROM cvr.cvr_jur_enhed_geo_stam stam
FULL OUTER JOIN cvr.cvr_jur_enhed_geo_hist_adresser hist ON stam.cvrnr = hist.cvrnr;




CREATE MATERIALIZED VIEW cvr.cvr_jur_ansatte_aar AS
SELECT
  stam.modifikationsstatus,
  stam.cvrnr,
  stam.livsforloeb_startdato,
  stam.livsforloeb_ophoersdato,
  stam.ajourfoeringsdato,
  stam.reklamebeskyttelse,
  stam.navn_gyldigfra,
  stam.navn_tekst,
  stam.beliggenhedsadresse_gyldigfra,
  stam.beliggenhedsadresse_vejnavn,
  stam.beliggenhedsadresse_vejkode,
  stam.belig_adresse_husnummerfra,
  stam.belig_adresse_husnummertil,
  stam.beliggenhedsadresse_bogstavfra,
  stam.beliggenhedsadresse_bogstavtil,
  stam.beliggenhedsadresse_etage,
  stam.beliggenhedsadresse_sidedoer,
  stam.beliggenhedsadresse_postnr,
  stam.belig_adresse_postdistrikt,
  stam.beliggenhedsadresse_bynavn,
  stam.kommune_kode,
  stam.kommune_tekst,
  stam.beliggenhedsadresse_postboks,
  stam.beliggenhedsadresse_conavn,
  stam.belig_adresse_adr_fritekst,
  stam.postadresse_gyldigfra,
  stam.postadresse_vejnavn,
  stam.postadresse_vejkode,
  stam.postadresse_husnummerfra,
  stam.postadresse_husnummertil,
  stam.postadresse_bogstavfra,
  stam.postadresse_bogstavtil,
  stam.postadresse_etage,
  stam.postadresse_sidedoer,
  stam.postadresse_postnr,
  stam.postadresse_postdistrikt,
  stam.postadresse_bynavn,
  stam.postadresse_kommune_kode,
  stam.postadresse_kommune_tekst,
  stam.postadresse_postboks,
  stam.postadresse_conavn,
  stam.postadresse_adressefritekst,
  stam.virksomhedsform_gyldigfra,
  stam.virksomhedsform_kode,
  stam.virksomhedsform_tekst,
  stam.virk_form_ans_datalev,
  stam.hovedbranche_gyldigfra,
  stam.hovedbranche_kode,
  stam.hovedbranche_tekst,
  stam.bibranche1_gyldigfra,
  stam.bibranche1_kode,
  stam.bibranche1_tekst,
  stam.bibranche2_gyldigfra,
  stam.bibranche2_kode,
  stam.bibranche2_tekst,
  stam.bibranche3_gyldigfra,
  stam.bibranche3_kode,
  stam.bibranche3_tekst,
  stam.telefonnummer_gyldigfra,
  stam.telefonnummer_kontaktoplysning,
  stam.telefax_gyldigfra,
  stam.telefax_kontaktoplysning,
  stam.email_gyldigfra,
  stam.email_kontaktoplysning,
  stam.kreditoplysning_gyldigfra,
  stam.kreditoplysning_tekst,

  hist.aarsbeskaeftigelse_aar,
  hist.aarsbes_antalansatte,
  hist.aarsbes_antansatteinterval,
  hist.aarsbes_antalaarsvaerk,
  hist.aarsbes_antaarsvaerkinterval,
  hist.aarsbes_antalinclejere,
  hist.aarsbes_antinclejereinterval,

  stam.kvartalsbeskaeftigelse_aar,
  stam.kvartalsbeskaeftigelse_kvartal,
  stam.kvartalsbes_antansatte,
  stam.kvartalsbes_antansatteinterval,
  stam.kvartalsbes_antalaarsvaerk,
  stam.kvartalsbes_antaarsvaerkinterval,
  stam.maanedsbeskaeftigelse_aar,
  stam.maanedsbeskaeftigelse_maaned,
  stam.maanedsbeskaeftigelse_antalansatte,
  stam.maanedsbeskaeftigelse_antalansatteinterval,
  stam.maanedsbeskaeftigelse_antalaarsvaerk,
  stam.maanedsbeskaeftigelse_antalaarsvaerkinterval,
  stam.produktionsenheder,
  stam.deltagere,
  stam.produktionsenheder_gyldigfra,
  stam.tilnaermethusnr,
  stam.geokodningskvalitet,
  stam.koornord,
  stam.kooroest,
  stam.lat,
  stam.long,
  stam.vejkode,
  stam.hus_nr,
  stam.husnr,
  stam.adr2,
  stam.lifasystemid,

  hist.indlaest_dato,

  stam.geom,
  stam.gid,

  hist.kilde
  FROM cvr.cvr_jur_enhed_geo_stam stam
FULL OUTER JOIN cvr.cvr_jur_enhed_geo_hist_ansatte_aar hist ON stam.cvrnr = hist.cvrnr;






CREATE MATERIALIZED VIEW cvr.cvr_jur_ansatte_kvartal AS
SELECT
  stam.modifikationsstatus,
  stam.cvrnr,
  stam.livsforloeb_startdato,
  stam.livsforloeb_ophoersdato,
  stam.ajourfoeringsdato,
  stam.reklamebeskyttelse,
  stam.navn_gyldigfra,
  stam.navn_tekst,
  stam.beliggenhedsadresse_gyldigfra,
  stam.beliggenhedsadresse_vejnavn,
  stam.beliggenhedsadresse_vejkode,
  stam.belig_adresse_husnummerfra,
  stam.belig_adresse_husnummertil,
  stam.beliggenhedsadresse_bogstavfra,
  stam.beliggenhedsadresse_bogstavtil,
  stam.beliggenhedsadresse_etage,
  stam.beliggenhedsadresse_sidedoer,
  stam.beliggenhedsadresse_postnr,
  stam.belig_adresse_postdistrikt,
  stam.beliggenhedsadresse_bynavn,
  stam.kommune_kode,
  stam.kommune_tekst,
  stam.beliggenhedsadresse_postboks,
  stam.beliggenhedsadresse_conavn,
  stam.belig_adresse_adr_fritekst,
  stam.postadresse_gyldigfra,
  stam.postadresse_vejnavn,
  stam.postadresse_vejkode,
  stam.postadresse_husnummerfra,
  stam.postadresse_husnummertil,
  stam.postadresse_bogstavfra,
  stam.postadresse_bogstavtil,
  stam.postadresse_etage,
  stam.postadresse_sidedoer,
  stam.postadresse_postnr,
  stam.postadresse_postdistrikt,
  stam.postadresse_bynavn,
  stam.postadresse_kommune_kode,
  stam.postadresse_kommune_tekst,
  stam.postadresse_postboks,
  stam.postadresse_conavn,
  stam.postadresse_adressefritekst,
  stam.virksomhedsform_gyldigfra,
  stam.virksomhedsform_kode,
  stam.virksomhedsform_tekst,
  stam.virk_form_ans_datalev,
  stam.hovedbranche_gyldigfra,
  stam.hovedbranche_kode,
  stam.hovedbranche_tekst,
  stam.bibranche1_gyldigfra,
  stam.bibranche1_kode,
  stam.bibranche1_tekst,
  stam.bibranche2_gyldigfra,
  stam.bibranche2_kode,
  stam.bibranche2_tekst,
  stam.bibranche3_gyldigfra,
  stam.bibranche3_kode,
  stam.bibranche3_tekst,
  stam.telefonnummer_gyldigfra,
  stam.telefonnummer_kontaktoplysning,
  stam.telefax_gyldigfra,
  stam.telefax_kontaktoplysning,
  stam.email_gyldigfra,
  stam.email_kontaktoplysning,
  stam.kreditoplysning_gyldigfra,
  stam.kreditoplysning_tekst,
  stam.aarsbeskaeftigelse_aar,
  stam.aarsbes_antalansatte,
  stam.aarsbes_antansatteinterval,
  stam.aarsbes_antalaarsvaerk,
  stam.aarsbes_antaarsvaerkinterval,
  stam.aarsbes_antalinclejere,
  stam.aarsbes_antinclejereinterval,

  hist.kvartalsbeskaeftigelse_aar,
  hist.kvartalsbeskaeftigelse_kvartal,
  hist.kvartalsbes_antansatte,
  hist.kvartalsbes_antansatteinterval,
  hist.kvartalsbes_antalaarsvaerk,
  hist.kvartalsbes_antaarsvaerkinterval,

  stam.maanedsbeskaeftigelse_aar,
  stam.maanedsbeskaeftigelse_maaned,
  stam.maanedsbeskaeftigelse_antalansatte,
  stam.maanedsbeskaeftigelse_antalansatteinterval,
  stam.maanedsbeskaeftigelse_antalaarsvaerk,
  stam.maanedsbeskaeftigelse_antalaarsvaerkinterval,
  stam.produktionsenheder,
  stam.deltagere,
  stam.produktionsenheder_gyldigfra,
  stam.tilnaermethusnr,
  stam.geokodningskvalitet,
  stam.koornord,
  stam.kooroest,
  stam.lat,
  stam.long,
  stam.vejkode,
  stam.hus_nr,
  stam.husnr,
  stam.adr2,
  stam.lifasystemid,

  hist.indlaest_dato,

  stam.geom,
  stam.gid,

  hist.kilde
  FROM cvr.cvr_jur_enhed_geo_stam stam
FULL OUTER JOIN cvr.cvr_jur_enhed_geo_hist_ansatte_kvartal hist ON stam.cvrnr = hist.cvrnr;



CREATE MATERIALIZED VIEW cvr.cvr_jur_hovedbranche AS
SELECT
  stam.modifikationsstatus,
  stam.cvrnr,
  stam.livsforloeb_startdato,
  stam.livsforloeb_ophoersdato,
  stam.ajourfoeringsdato,
  stam.reklamebeskyttelse,
  stam.navn_gyldigfra,
  stam.navn_tekst,
  stam.beliggenhedsadresse_gyldigfra,
  stam.beliggenhedsadresse_vejnavn,
  stam.beliggenhedsadresse_vejkode,
  stam.belig_adresse_husnummerfra,
  stam.belig_adresse_husnummertil,
  stam.beliggenhedsadresse_bogstavfra,
  stam.beliggenhedsadresse_bogstavtil,
  stam.beliggenhedsadresse_etage,
  stam.beliggenhedsadresse_sidedoer,
  stam.beliggenhedsadresse_postnr,
  stam.belig_adresse_postdistrikt,
  stam.beliggenhedsadresse_bynavn,
  stam.kommune_kode,
  stam.kommune_tekst,
  stam.beliggenhedsadresse_postboks,
  stam.beliggenhedsadresse_conavn,
  stam.belig_adresse_adr_fritekst,
  stam.postadresse_gyldigfra,
  stam.postadresse_vejnavn,
  stam.postadresse_vejkode,
  stam.postadresse_husnummerfra,
  stam.postadresse_husnummertil,
  stam.postadresse_bogstavfra,
  stam.postadresse_bogstavtil,
  stam.postadresse_etage,
  stam.postadresse_sidedoer,
  stam.postadresse_postnr,
  stam.postadresse_postdistrikt,
  stam.postadresse_bynavn,
  stam.postadresse_kommune_kode,
  stam.postadresse_kommune_tekst,
  stam.postadresse_postboks,
  stam.postadresse_conavn,
  stam.postadresse_adressefritekst,
  stam.virksomhedsform_gyldigfra,
  stam.virksomhedsform_kode,
  stam.virksomhedsform_tekst,
  stam.virk_form_ans_datalev,

  hist.hovedbranche_gyldigfra,
  hist.hovedbranche_kode,
  hist.hovedbranche_tekst,

  stam.bibranche1_gyldigfra,
  stam.bibranche1_kode,
  stam.bibranche1_tekst,
  stam.bibranche2_gyldigfra,
  stam.bibranche2_kode,
  stam.bibranche2_tekst,
  stam.bibranche3_gyldigfra,
  stam.bibranche3_kode,
  stam.bibranche3_tekst,
  stam.telefonnummer_gyldigfra,
  stam.telefonnummer_kontaktoplysning,
  stam.telefax_gyldigfra,
  stam.telefax_kontaktoplysning,
  stam.email_gyldigfra,
  stam.email_kontaktoplysning,
  stam.kreditoplysning_gyldigfra,
  stam.kreditoplysning_tekst,
  stam.aarsbeskaeftigelse_aar,
  stam.aarsbes_antalansatte,
  stam.aarsbes_antansatteinterval,
  stam.aarsbes_antalaarsvaerk,
  stam.aarsbes_antaarsvaerkinterval,
  stam.aarsbes_antalinclejere,
  stam.aarsbes_antinclejereinterval,
  stam.kvartalsbeskaeftigelse_aar,
  stam.kvartalsbeskaeftigelse_kvartal,
  stam.kvartalsbes_antansatte,
  stam.kvartalsbes_antansatteinterval,
  stam.kvartalsbes_antalaarsvaerk,
  stam.kvartalsbes_antaarsvaerkinterval,
  stam.maanedsbeskaeftigelse_aar,
  stam.maanedsbeskaeftigelse_maaned,
  stam.maanedsbeskaeftigelse_antalansatte,
  stam.maanedsbeskaeftigelse_antalansatteinterval,
  stam.maanedsbeskaeftigelse_antalaarsvaerk,
  stam.maanedsbeskaeftigelse_antalaarsvaerkinterval,
  stam.produktionsenheder,
  stam.deltagere,
  stam.produktionsenheder_gyldigfra,
  stam.tilnaermethusnr,
  stam.geokodningskvalitet,
  stam.koornord,
  stam.kooroest,
  stam.lat,
  stam.long,
  stam.vejkode,
  stam.hus_nr,
  stam.husnr,
  stam.adr2,
  stam.lifasystemid,

  hist.indlaest_dato,

  stam.geom,
  stam.gid,

  hist.kilde
  FROM cvr.cvr_jur_enhed_geo_stam stam
FULL OUTER JOIN cvr.cvr_jur_enhed_geo_hist_hovedbranche hist ON stam.cvrnr = hist.cvrnr;



